### ISSUE TITLE
Running Initial Toy Example 

### ISSUE THREAD

**Issue by Ulvetanna** [vlehtola/icepathfinder#1]
Hi All :) 

I am wanting to run an initial example for the codebase, but having issues sourcing some of the required files.

Currently it seems that a HELMI grid is required to run the example. I was wondering if you could supply `helmigri_20110320_0600` or do you have another toy example that can be run. 

Thanks in advance ! :)

**Comment by Ulvetanna** [comment]
Just tagging developer @vlehtola

**Comment by vlehtola** [comment]
Unfortunately, the data was not fully open at that time. Perhaps the issue has been already resolved. Please check e.g. [here](https://data.europa.eu/data/catalogues/fmi?locale=en )
